import 'package:handlerify/services/session_service.dart';
import 'package:injectable/injectable.dart';
import 'package:intl/intl.dart';

import '../models/session.dart';

@dev
@test
@injectable
class SessionController {

  final SessionService sessionService;
  Session session = Session.empty();

  SessionController(SessionService this.sessionService);

  String _autogenerateTitle(DateTime startTime, int sessionNumber) {
    final DateFormat formatter = DateFormat('MMMd');
    return formatter.format(startTime) + " Session " + sessionNumber.toString();
  }

  // returns the autogenerated title for display
  Future<String> start() async {
    int count = await sessionService.getTodayCount();
    int sessionNumber = count + 1;

    session.startTime = DateTime.now();
    session.title = _autogenerateTitle(session.startTime!, sessionNumber);

    return session.title!;
  }

  // TODO
  void save() {
    sessionService.create(session);
  }

  void pause() {

  }

  void resume() {

  }

  void delete() {

  }

}